# Generated by Django 2.0.4 on 2018-05-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flap',
            name='head',
        ),
        migrations.AddField(
            model_name='flap',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flaps', to='flips.Head'),
        ),
    ]
